# Script de nettoyage agressif - Skills business/marketing/non-tech
$basePath = "C:\Users\jawis\OneDrive\Desktop\sahbi\.windsurf\skills"

$patternsToRemove = @(
    # Business / Marketing / Startup (non tech)
    "marketing-ideas",
    "marketing-psychology",
    "market-sizing-analysis",
    "competitive-landscape",
    "competitor-alternatives",
    "startup-analyst",
    "startup-business-analyst-*",
    "startup-financial-modeling",
    "startup-metrics-framework",
    "product-manager-toolkit",
    "business-analyst",
    "data-storytelling",
    "market-sizing-analysis",
    "team-composition-analysis",
    "pricing-strategy",
    "customer-support",
    "sales-automator",
    "referral-program",
    "launch-strategy",
    "free-tool-strategy",
    "viral-generator-builder",
    "micro-saas-launcher",
    "personal-tool-builder",
    "ai-wrapper-product",
    "content-creator",
    "content-marketer",
    "social-content",
    "paid-ads",
    "email-sequence",
    "email-systems",
    "copywriting",
    "copy-editing",
    "seo-*",
    "programmatic-seo",
    "page-cro",
    "form-cro",
    "popup-cro",
    "signup-flow-cro",
    "onboarding-cro",
    "paywall-upgrade-cro",
    "ab-test-setup",
    # HR / Legal / Business docs
    "hr-pro",
    "legal-advisor",
    "employment-contract-templates",
    "billing-automation",
    # Quant/Finance (non pertinent)
    "quant-analyst",
    "risk-manager",
    "risk-metrics-calculation",
    "backtesting-frameworks",
    # AI/ML spécifiques (pas utilisés dans ce projet)
    "ai-engineer",
    "ai-product",
    "ai-agents-architect",
    "ai-wrapper-product",
    "computer-vision-expert",
    "deep-research",
    # Sécurité offensive restante
    "reverse-engineer",
    "threat-modeling-expert",
    "vulnerability-scanner",
    "stride-analysis-patterns",
    "threat-mitigation-mapping",
    "security-requirement-extraction",
    "pentest-*",
    "red-team-*",
    "network-101",
    "protocol-reverse-engineering",
    "binary-analysis-patterns",
    "sharp-edges",
    "sast-configuration",
    "security-scanning-*",
    # Game dev / Rust desktop
    "makepad-skills",
    # Langages non utilisés (vérifier s'il en reste)
    "python-*",
    "java-*",
    "csharp-*",
    "dotnet-*",
    "php-*",
    "ruby-*",
    "golang-*",
    "elixir-*",
    "scala-*",
    "haskell-*",
    "julia-*",
    "c-pro",
    "cpp-pro",
    "rust-pro",
    "rust-async-patterns",
    "systems-programming-rust-project",
    # Mobile (vérifier s'il en reste)
    "flutter-*",
    "ios-*",
    "swift*",
    "react-native-*",
    "expo-*",
    "mobile-*",
    "app-store-optimization",
    # Cloud/K8s/Terraform (vérifier s'il en reste)
    "azure-*",
    "aws-*",
    "gcp-*",
    "terraform-*",
    "kubernetes-*",
    "k8s-*",
    "helm-*",
    "istio-*",
    "linkerd-*",
    "cloud-*",
    "hybrid-*",
    "multi-cloud-*",
    "cost-optimization",
    "server-management",
    # Database non utilisées
    "dbos-*",
    "azure-cosmos-*",
    "azure-data-*",
    "azure-postgres-*",
    "azure-mysql-*",
    "azure-sql-*",
    "azure-redis-*",
    "neon-*",
    "using-neon",
    "nosql-expert",
    "clickhouse-*",
    "mongodb-*",
    "dynamodb-*",
    "cassandra-*",
    # Backend frameworks non utilisés
    "nestjs-*",
    "fastapi-*",
    "django-*",
    "flask-*",
    "laravel-*",
    "moodle-*",
    # Job queues / Background (non utilisés)
    "bullmq-*",
    "inngest",
    "trigger-dev",
    "upstash-*",
    "temporal-*",
    # Data engineering
    "airflow-*",
    "spark-*",
    "dbt-*",
    "data-engineering-*",
    "data-quality-*",
    "ml-*",
    "mlops-*",
    "machine-learning-*",
    # Blockchain/Web3
    "blockchain-*",
    "defi-*",
    "nft-*",
    "solidity-*",
    "web3-*",
    "crypto-*",
    # Desktop/Frameworks spécifiques
    "avalonia-*",
    "m365-*",
    "microsoft-*",
    # LLM/Agents spécifiques (déjà supprimés mais vérifier)
    "crewai",
    "langchain-*",
    "langfuse",
    "langgraph",
    "autonomous-*",
    "agent-*",
    "agents-*",
    "hosted-agents-*",
    "copilot-sdk",
    # Outils spécifiques
    "n8n-*",
    "zapier-*",
    "makepad-*",
    # Notion/Obsidian
    "notion-*",
    "obsidian-*",
    "notebooklm",
    # Audio/Video
    "podcast-*",
    "audio-*",
    "voice-*",
    "youtube-*",
    "remotion-*",
    # Documents
    "pptx*",
    "docx*",
    "xlsx*",
    "pdf",
    "pdf-official",
    # Recherche/Web scraping
    "firecrawl-*",
    "tavily-*",
    "exa-*",
    "shodan-*",
    # 3D/Design
    "threejs-*",
    "3d-*",
    "algorithmic-art",
    "canvas-design",
    "scroll-experience",
    "interactive-portfolio",
    "stitch-ui-design",
    "theme-factory",
    "nanobanana-*",
    "frontend-slides",
    "slack-gif-creator",
    # Meta/outils Claude
    "claude-*-skill",
    "claude-code-guide",
    "claude-ally-health",
    "claude-scientific-skills",
    "claude-d3js-skill",
    "claude-speed-reader",
    "claude-win11-speckit-update-skill",
    "infinite-gratitude",
    "superpowers-lab",
    "using-superpowers",
    "loki-mode",
    "spdd",
    "3d-web-experience",
    # Search/Index
    "algolia-*",
    "cc-skill-*",
    "daily-news-report",
    "vexor",
    "culture-index",
    "notebooklm",
    # Pydantic/Python (pas utilisé)
    "pydantic-*",
    "python-*",
    "uv-*",
    # Specific skills
    "ffuf-*",
    "pypict-*",
    "varlock-*",
    "blockrun",
    "imagen",
    "fal-*",
    "hugging-face-*",
    "gemini-api-dev",
    "hugging-face-*",
    # Devops (si pas utilisé)
    "docker-expert",
    "gitops-*",
    "gitlab-ci-*",
    "circleci-*",
    "github-actions-templates",
    # Misc
    "geo-fundamentals",
    "google-search-console",
    "ahrefs-*",
    "moz-*",
    "screaming-frog-*",
    "semrush-*",
    "openai-*"
)

Write-Host "Nettoyage agressif des skills non-tech/business..." -ForegroundColor Yellow
$count = 0

foreach ($pattern in $patternsToRemove) {
    $paths = Get-ChildItem -Path $basePath -Filter $pattern -Directory -ErrorAction SilentlyContinue
    foreach ($path in $paths) {
        try {
            Remove-Item -Path $path.FullName -Recurse -Force -ErrorAction Stop
            Write-Host "  Supprimé: $($path.Name)" -ForegroundColor Red
            $count++
        }
        catch {
            # Silencieux pour les erreurs
        }
    }
}

Write-Host "`nTotal supprimé dans ce batch: $count skills" -ForegroundColor Green
$remaining = (Get-ChildItem -Path $basePath -Directory | Measure-Object).Count
Write-Host "Skills restants: $remaining" -ForegroundColor Cyan
