# Script de suppression massive des skills non pertinents
# Projet: Next.js + React + TypeScript + Convex + Clerk + Tailwind

$basePath = "C:\Users\jawis\OneDrive\Desktop\sahbi\.windsurf\skills"

# Patterns à supprimer (non pertinents pour ce projet)
$patternsToRemove = @(
    # Azure (tous)
    "azure-*",
    # AWS
    "aws-*",
    # Pentesting / Sécurité offensive
    "active-directory-attacks",
    "api-fuzzing-bug-bounty",
    "aws-penetration-testing",
    "cloud-penetration-testing",
    "anti-reversing-techniques",
    "attack-tree-construction",
    "broken-authentication",
    "burp-suite-testing",
    "ethical-hacking-methodology",
    "file-path-traversal",
    "html-injection-testing",
    "idor-testing",
    "linux-privilege-escalation",
    "linux-shell-scripting",
    "metasploit-framework",
    "pentest-checklist",
    "pentest-commands",
    "privilege-escalation-methods",
    "red-team-tactics",
    "red-team-tools",
    "scanning-tools",
    "security-bluebook-builder",
    "shodan-reconnaissance",
    "smtp-penetration-testing",
    "sql-injection-testing",
    "sqlmap-database-pentesting",
    "ssh-penetration-testing",
    "top-web-vulnerabilities",
    "windows-privilege-escalation",
    "wireshark-analysis",
    "wordpress-penetration-testing",
    "xss-html-injection",
    "malware-analyst",
    "memory-forensics",
    "firmware-analyst",
    # Game Development
    "game-development",
    "unity-developer",
    "unity-ecs-patterns",
    "unreal-engine-cpp-pro",
    "godot-gdscript-patterns",
    "minecraft-bukkit-pro",
    # Mobile Development
    "ios-developer",
    "flutter-expert",
    "react-native-architecture",
    "swiftui-expert-skill",
    "mobile-design",
    "mobile-developer",
    "mobile-security-coder",
    "expo-deployment",
    "upgrading-expo",
    # Langages non utilisés
    "java-pro",
    "python-pro",
    "csharp-pro",
    "php-pro",
    "ruby-pro",
    "elixir-pro",
    "scala-pro",
    "golang-pro",
    "julia-pro",
    "haskell-pro",
    "c-pro",
    "cpp-pro",
    "rust-pro",
    "rust-async-patterns",
    # Frameworks backend non utilisés
    "django-pro",
    "laravel-expert",
    "laravel-security-audit",
    "nestjs-expert",
    "fastapi-*",
    "moodle-external-api-development",
    # CRM / Automation tools
    "activecampaign-automation",
    "airtable-automation",
    "asana-automation",
    "bamboohr-automation",
    "basecamp-automation",
    "bitbucket-automation",
    "brevo-automation",
    "cal-com-automation",
    "calendly-automation",
    "canva-automation",
    "circleci-automation",
    "clickup-automation",
    "close-automation",
    "coda-automation",
    "confluence-automation",
    "convertkit-automation",
    "datadog-automation",
    "discord-automation",
    "discord-bot-architect",
    "docusign-automation",
    "dropbox-automation",
    "facebook-lead-ads",
    "figma-automation",
    "freshdesk-automation",
    "freshservice-automation",
    "github-automation",
    "github-workflow-automation",
    "gitlab-automation",
    "gmail-automation",
    "google-analytics-automation",
    "google-calendar-automation",
    "google-drive-automation",
    "googlesheets-automation",
    "helpdesk-automation",
    "hubspot-automation",
    "hubspot-integration",
    "instagram-automation",
    "intercom-automation",
    "jira-automation",
    "klaviyo-automation",
    "linkedin-automation",
    "mailchimp-automation",
    "make-automation",
    "microsoft-teams-automation",
    "miro-automation",
    "mixpanel-automation",
    "monday-automation",
    "notion-automation",
    "one-drive-automation",
    "outlook-automation",
    "outlook-calendar-automation",
    "pagerduty-automation",
    "pipedrive-automation",
    "posthog-automation",
    "postmark-automation",
    "reddit-automation",
    "salesforce-automation",
    "salesforce-development",
    "segment-automation",
    "segment-cdp",
    "sendgrid-automation",
    "sentry-automation",
    "shopify-automation",
    "shopify-apps",
    "shopify-development",
    "slack-automation",
    "slack-bot-builder",
    "square-automation",
    "stripe-automation",
    "supabase-automation",
    "telegram-automation",
    "telegram-bot-builder",
    "telegram-mini-app",
    "tiktok-automation",
    "todoist-automation",
    "trello-automation",
    "twitter-automation",
    "webflow-automation",
    "whatsapp-automation",
    "wrike-automation",
    "x-article-publisher-skill",
    "youtube-automation",
    "zendesk-automation",
    "zoho-crm-automation",
    "zoom-automation",
    "automate-whatsapp",
    "observe-whatsapp",
    "linear-automation",
    "linear-claude-skill",
    "amplitude-automation",
    "box-automation",
    "render-automation",
    "vercel-automation",
    # Job queues / Background jobs (non utilisés)
    "bullmq-specialist",
    "inngest",
    "trigger-dev",
    "upstash-qstash",
    "temporal-python-*",
    # Web scraping / Research
    "firecrawl-scraper",
    "tavily-web",
    "exa-search",
    "deep-research",
    # AI/ML génération
    "fal-*",
    "imagen",
    "hugging-face-*",
    "gemini-api-dev",
    "blockrun",
    # Data Engineering
    "dbt-transformation-patterns",
    "airflow-dag-patterns",
    "spark-optimization",
    "data-quality-frameworks",
    "data-engineering-*",
    # ML/Data Science
    "ml-engineer",
    "ml-pipeline-workflow",
    "mlops-engineer",
    "machine-learning-ops-ml-pipeline",
    "data-scientist",
    # Blockchain/Web3
    "blockchain-developer",
    "defi-protocol-templates",
    "nft-standards",
    "solidity-security",
    "web3-testing",
    "crypto-bd-agent",
    # K8s / Service Mesh
    "kubernetes-*",
    "istio-*",
    "linkerd-*",
    "k8s-*",
    "helm-*",
    # Cloud / Terraform
    "terraform-*",
    "kubernetes-architect",
    "cloud-architect",
    "hybrid-cloud-*",
    "cost-optimization",
    "mtls-configuration",
    "secrets-management",
    "multi-cloud-*",
    "service-mesh-*",
    # DevOps
    "distributed-tracing",
    "gitops-workflow",
    "gitlab-ci-patterns",
    # Observabilité (si pas utilisée)
    "grafana-dashboards",
    "prometheus-configuration",
    "loki-mode",
    "slo-implementation",
    # Patterns avancés (si pas utilisés)
    "saga-orchestration",
    "event-sourcing-architect",
    "cqrs-implementation",
    "microservices-patterns",
    # Monorepo (si pas utilisé)
    "nx-workspace-patterns",
    "turborepo-caching",
    "monorepo-*",
    "bazel-build-optimization",
    # Build tools / Automation
    "n8n-*",
    "zapier-*",
    "pypict-skill",
    "ffuf-claude-skill",
    # 3D / Design Art
    "spdd",
    "3d-web-experience",
    "threejs-skills",
    "algorithmic-art",
    "scroll-experience",
    # UI / Portfolio / PPT
    "interactive-portfolio",
    "viral-generator-builder",
    "stitch-ui-design",
    "theme-factory",
    "nanobanana-ppt-skills",
    "slack-gif-creator",
    "frontend-slides",
    "pptx*",
    "docx*",
    "xlsx*",
    # Notion / Obsidian
    "obsidian-clipper-template-creator",
    "notebooklm",
    "notion-template-business",
    "cc-skill-*",
    "daily-news-report",
    # Audio / Vidéo
    "youtube-summarizer",
    "audio-transcriber",
    "podcast-generation",
    "voice-*",
    "voice-ai-*",
    # SEO outils spécifiques
    "google-search-console",
    "ahrefs-seo",
    "moz-seo",
    "screaming-frog-seo",
    "semrush-seo",
    # Frameworks Desktop
    "avalonia-*",
    "dotnet-*",
    "m365-*",
    "microsoft-*",
    # LLM Frameworks
    "crewai",
    "langchain-*",
    "langfuse",
    "langgraph",
    "llm-*",
    "prompt-*",
    "context-*",
    "conversation-memory",
    # Autres
    "infinite-gratitude",
    "oss-hunter",
    "app-store-optimization",
    "geo-fundamentals",
    "pdf",
    "pdf-official",
    # Databases (si pas utilisées)
    "dbos-*",
    "azure-cosmos-*",
    "azure-data-*",
    "azure-eventhub-*",
    "azure-servicebus-*",
    "azure-storage-*",
    "azure-identity-*",
    "azure-keyvault-*",
    "azure-functions",
    "azure-maps-*",
    "azure-web-pubsub-ts",
    "nosql-expert",
    # Frontend UI spécifiques (si non utilisés)
    "radix-ui-design-system",
    # Systems programming
    "systems-programming-rust-project",
    "arm-cortex-expert",
    # Skills Claude spécifiques
    "claude-d3js-skill",
    "claude-speed-reader",
    "claude-win11-speckit-update-skill",
    "claude-code-guide",
    "claude-ally-health",
    "claude-scientific-skills"
)

Write-Host "Suppression massive des skills non pertinents..." -ForegroundColor Yellow
$count = 0

foreach ($pattern in $patternsToRemove) {
    $paths = Get-ChildItem -Path $basePath -Filter $pattern -Directory -ErrorAction SilentlyContinue
    foreach ($path in $paths) {
        try {
            Remove-Item -Path $path.FullName -Recurse -Force -ErrorAction Stop
            Write-Host "Supprimé: $($path.Name)" -ForegroundColor Red
            $count++
        }
        catch {
            Write-Host "Erreur lors de la suppression de $($path.Name): $_" -ForegroundColor DarkYellow
        }
    }
}

Write-Host "`nTotal supprimé: $count skills" -ForegroundColor Green
Write-Host "Skills restants:" -ForegroundColor Cyan
Get-ChildItem -Path $basePath -Directory | Select-Object -ExpandProperty Name | Sort-Object
